#!/bin/bash

BUILD_DIR="./build"
DATA_DIR="./kernel/data"

TARGET="$BUILD_DIR"

if [ "$1" == "--data" ]; then
    TARGET="$DATA_DIR"
fi

if [ -d "$TARGET" ]; then
    rm -rf "$TARGET"/*
    echo "✅ Cleaned all files in $TARGET"
else
    echo "⚠️  Directory $TARGET does not exist"
fi
